print('Estructura principal')
print('Módulo Login: Activo')
print('FUNCIONALIDAD: Validación de credenciales de usuario')
print('Registro de Usuarios')
print('FUNCIONALIDAD: Creación de nuevos perfiles en el sistema')
print('Interfaz Frontend: Renderizada')
print('FUNCIONALIDAD: Interfaz de usuario con diseño responsivo')
print('Servidor Backend: Activo')
print('FUNCIONALIDAD: Procesamiento de datos en el servidor')
print('Base de datos')
print('FUNCIONALIDAD: Almacenamiento persistente en base de datos SQL')

